services:
  weather-app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    tty: true
    # command: >
    #   /bin/bash -c '
    #   cd app/ &&
    #   npm ci --cache /tmp/empty-cache &&
    #   npm run dev
    #   '
